In [29]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [30]:
df = pd.read_csv('movie_metadata1.csv')
del df['Unnamed: 0']
del df['Unnamed: 0.1']
print(len(df))
print(list(df))
df.head()

4924
['color', 'director_name', 'num_critic_for_reviews', 'duration', 'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name', 'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link', 'num_user_for_reviews', 'language', 'country', 'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [31]:
dicc_directores = dict()
count = 0
array = []
for i in df['director_name']:
    if i not in dicc_directores.keys():
        count = count + 1
        dicc_directores.update({i:count})
    array.append(dicc_directores[i])
#print(array)
#print(dicc_directores)
df['director_name'] = array

In [32]:
array = []
a = df['num_critic_for_reviews'][4]
for i in df['num_critic_for_reviews']:
    if np.isnan(i):
        i = 0
    array.append(i)
df['num_critic_for_reviews'] = array

In [33]:
array = []
a = df['duration'][4]
for i in df['duration']:
    if np.isnan(i):
        i = 0
    array.append(i)
df['duration'] = array

In [34]:
array = []
a = df['gross'][4]
for i in df['gross']:
    if np.isnan(i):
        i = 0
    array.append(i)
df['gross'] = array

In [35]:
dicc_genres = dict()
count = 0
array = []
print(df['genres'][0].split('|'))
for values in df['genres']:
    a = []
    for i in values.split('|'):
        if i not in dicc_genres.keys():
            count = count + 1
            dicc_genres.update({i:count})
        a.append(dicc_genres[i])
    array.append(a)
df['genres'] = array

['Action', 'Adventure', 'Fantasy', 'Sci-Fi']

In [36]:
dicc_actores1 = dict()
count = 0
array = []
for i in df['actor_1_name']:
    if i not in dicc_actores1.keys():
        count = count + 1
        dicc_actores1.update({i:count})
    array.append(dicc_actores1[i])
#print(array)
#print(dicc_actores1)
df['actor_1_name'] = array

In [37]:
#movie_title
dicc_titulos = dict()
count = 0
array = []
print(len(df['movie_title']))
for i in df['movie_title']:
    if i not in dicc_titulos:
        count = count + 1
        dicc_titulos.update({i:count})
    array.append(dicc_titulos[i])
print(len(array))
#print(array)
print(np.unique(array,return_index=True))
print(len(dicc_titulos))
dupes = [x for n, x in enumerate(array) if x in array[:n]]
print((set(dupes)))

4924
4924
(array([   1,    2,    3, ..., 4802, 4803, 4804]), array([   0,    1,    2, ..., 4921, 4922, 4923], dtype=int32))
4804
{7, 2576, 17, 1042, 24, 2073, 2074, 28, 3612, 30, 34, 35, 1058, 3621, 44, 3118, 1583, 1589, 56, 1089, 71, 75, 1616, 1623, 88, 89, 1113, 1631, 1125, 4715, 620, 3705, 2684, 1676, 1171, 170, 2743, 695, 1727, 192, 2757, 209, 3795, 222, 3295, 225, 740, 1766, 2790, 1256, 2287, 246, 254, 768, 258, 259, 2307, 1292, 1807, 274, 276, 284, 287, 1311, 2339, 2856, 1322, 303, 2864, 2353, 304, 823, 314, 1851, 1855, 2374, 1352, 841, 2888, 332, 3406, 1871, 1874, 2911, 353, 2402, 1379, 1892, 1391, 2424, 1921, 388, 390, 1929, 1419, 919, 2459, 1443, 427, 1454, 946, 1973, 950, 4024, 3001, 2497, 2501, 3535, 2513, 2515, 3035, 1518, 2031, 1007}